apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/gallad51/lnkubernetes-test/backend:${{ SHA }}
          # {"$imagepolicy": "flux-system:backend"}
          ports:
            - containerPort: 3000
