apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: backend
  namespace: flux-system
spec:
  image: ghcr.io/gallad51/lnkubernetes-test/backend
  interval: 1m
  secretRef:
    name: ghcr-auth
