apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - dragonfly-deployment.yaml
  - dragonfly-service.yaml
  - dragonfly-pvc.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - mongo-pvc.yaml
  - ingress.yaml
